### ISSUE TITLE
感谢您的fyne教学

### ISSUE THREAD

**Issue by longsizhuo** [thh9/bigbrother#1]
请问您的 ` &fyne.StaticResource` 是在哪里获取的呢，当我读fyne文档的时候只找到了`fyne.Resource`。多有打扰，抱歉。

**Comment by longsizhuo** [comment]
2023/08/07 03:13:25 Fyne error:  font load error
2023/08/07 03:13:25   Cause: freetype: invalid TrueType format: bad TTF version

不清楚这个报错的原因，第一次打开成功有gui，但是再次打开后就报错了

**Comment by longsizhuo** [comment]
已解决：该方法不适用于OTF格式，只适用于TTF格式

**Comment by abandon1a2b** [comment]
> 请问您的 ` &fyne.StaticResource` 是在哪里获取的呢，当我读fyne文档的时候只找到了`fyne.Resource`。多有打扰，抱歉。

Resource 是一个接口，goland 提示有那些接口实现了这个，
<img width="728" alt="image" src="https://github.com/eatmeatball/bigbrother/assets/28970107/6d24cd5c-57a0-46da-bcd3-b3615965f741">

还有你提到的这个报错也是我项目中的么，我在项目中内置了一份华为的免费字体，为了防止生成文件过大，用的go:embed引入此文件。没有用官网提供的脚手架去转化。正常情况下应该可以运行和显示汉字

**Comment by longsizhuo** [comment]
> > 请问您的 ` &fyne.StaticResource` 是在哪里获取的呢，当我读fyne文档的时候只找到了`fyne.Resource`。多有打扰，抱歉。
> 
> Resource 是一个接口，goland 提示有那些接口实现了这个， <img alt="image" width="728" src="https://user-images.githubusercontent.com/28970107/258781875-6d24cd5c-57a0-46da-bcd3-b3615965f741.png">
> 
> 还有你提到的这个报错也是我项目中的么，我在项目中内置了一份华为的免费字体，为了防止生成文件过大，用的go:embed引入此文件。没有用官网提供的脚手架去转化。正常情况下应该可以运行和显示汉字

学到了谢谢，我是自己下载了微软的字体，用这个方式报错了，所以才来开了个issue，换回原字体就解决了
